### PR TITLE
add clowder fact

### PR DESCRIPTION
**Pull request by laboon**

### CODE REVIEW

**Comment by carols10cents** [comment]
Hmm, can you add what a group of kittens is called too?

**Comment by laboon** [comment]
Added, can you re-review?

(btw I am doing this for my "intro to git" class, hope you don't mind!)

**Comment by carols10cents** [comment]
I don't mind at all!! :) Would you like to demonstrate squashing 2 commits into one? :)

**Comment by laboon** [comment]
Naah not for this.  I'm already trying to squeeze quite a bit into a relatively short presentation... thanks for the opportunity, though!

**Comment by carols10cents** [comment]
Should I merge? :)

**Comment by laboon** [comment]
YES PEOPLE NEED TO KNOW ABOUT CLOWDERS AND KINDLES

(caps lock notwithstanding, whichever you prefer, honestly)

**Comment by carols10cents** [comment]
DONE. PLZ EXTEND HAND TO RECEIVE EMOJI 🐈😻

**Comment by laboon** [comment]
:hand:

**Pull request merged**
